export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  ORDER_MANAGER = 'ORDER_MANAGER',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  MARKETING = 'MARKETING',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  CUSTOMER = 'CUSTOMER',
  GUEST = 'GUEST',
}

export enum Permission {
  // Product & Inventory
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_READ = 'PRODUCT_READ',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',

  INVENTORY_MANAGE = 'INVENTORY_MANAGE',

  // Orders
  ORDER_READ = 'ORDER_READ',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_REFUND = 'ORDER_REFUND',

  // Customer
  CUSTOMER_READ = 'CUSTOMER_READ',
  CUSTOMER_UPDATE = 'CUSTOMER_UPDATE',

  // Discounts / Marketing
  COUPON_MANAGE = 'COUPON_MANAGE',
  BANNER_MANAGE = 'BANNER_MANAGE',
  CAMPAIGN_MANAGE = 'CAMPAIGN_MANAGE',

  // Content
  CMS_MANAGE = 'CMS_MANAGE',
  BLOG_MANAGE = 'BLOG_MANAGE',

  // Accounting
  FINANCE_READ = 'FINANCE_READ',

  // Reports
  REPORT_VIEW = 'REPORT_VIEW',

  // System
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',
  ROLE_MANAGE = 'ROLE_MANAGE',
}
